//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreezingManApp.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Camp
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string MainImagePath { get; set; }
        public Nullable<int> PositionX { get; set; }
        public Nullable<int> PositionY { get; set; }
        public int TypeId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string Description { get; set; }
        public Nullable<System.TimeSpan> StartWorkingTime { get; set; }
        public Nullable<System.TimeSpan> EndWorkingTime { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual Type Type { get; set; }
    }
}
